language: python
cache: pip
matrix:
    include:
        - { python: '3.5', env: TOX_ENV=py35}
        - { python: '3.6', env: TOX_ENV=py36}
        - { python: '3.7-dev', env: TOX_ENV=py37}
before_install:
  - pip install codecov
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
after_success:
    - tox -e coverage-report
    - codecov
